import { useCallback, useEffect, useMemo, useState } from 'react';
import { COMMON_CREATURE_TYPES, type Card } from '../models/card';
import type { Deck } from '../models/deck';
import {
  createAiOpponent,
  deleteAiOpponent,
  loadAiOpponents,
  resolveAiOpponentDeck,
  saveAiOpponent,
  updateAiOpponent,
  validateAiOpponent,
  type AiOpponent,
  type AiOpponentDeckSource,
} from '../storage/aiOpponentStorage';
import { loadDecks } from '../storage/deckStorage';
import { loadCards } from '../storage/cardStorage';
import type { AutoDeckDifficulty, AutoDeckStyle } from '../engine/autoDeckBuilder';
import './AiOpponentsPage.css';

const AUTO_DIFFICULTIES: AutoDeckDifficulty[] = ['easy', 'normal', 'hard'];
const AUTO_STYLES: AutoDeckStyle[] = [
  'random',
  'balanced',
  'aggressive',
  'defensive',
  'big-monsters',
  'cheap-swarm',
];

interface OpponentFormState {
  name: string;
  portraitImageUrl: string;
  difficulty: AutoDeckDifficulty;
  playStyle: AutoDeckStyle;
  deckSource: AiOpponentDeckSource;
  savedDeckId: string;
  includeLegendary: boolean;
  preferredCreatureType: string;
  catchphrase: string;
}

function labelAutoStyle(style: AutoDeckStyle): string {
  switch (style) {
    case 'random':
      return 'Random';
    case 'balanced':
      return 'Balanced';
    case 'aggressive':
      return 'Aggressive';
    case 'defensive':
      return 'Defensive';
    case 'big-monsters':
      return 'Big Monsters';
    case 'cheap-swarm':
      return 'Cheap Swarm';
  }
}

function labelDeckSource(source: AiOpponentDeckSource): string {
  return source === 'savedDeck' ? 'Saved Deck' : 'Auto Generated';
}

function createEmptyForm(savedDeckId = ''): OpponentFormState {
  return {
    name: '',
    portraitImageUrl: '',
    difficulty: 'normal',
    playStyle: 'balanced',
    deckSource: 'autoGenerated',
    savedDeckId,
    includeLegendary: true,
    preferredCreatureType: '',
    catchphrase: '',
  };
}

export function AiOpponentsPage() {
  const [opponents, setOpponents] = useState<AiOpponent[]>([]);
  const [decks, setDecks] = useState<Deck[]>([]);
  const [cards, setCards] = useState<Card[]>([]);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<OpponentFormState>(createEmptyForm());
  const [previewDeck, setPreviewDeck] = useState<Deck | null>(null);
  const [previewOpponent, setPreviewOpponent] = useState<AiOpponent | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  const cardsById = useMemo(() => new Map(cards.map((card) => [card.id, card])), [cards]);

  const refresh = useCallback(() => {
    const nextErrors: string[] = [];
    let loadedDecks: Deck[] = [];

    try {
      loadedDecks = loadDecks();
      setDecks(loadedDecks);
    } catch (err) {
      setDecks([]);
      nextErrors.push(err instanceof Error ? err.message : 'Could not load decks.');
    }

    try {
      setOpponents(loadAiOpponents());
    } catch (err) {
      setOpponents([]);
      nextErrors.push(err instanceof Error ? err.message : 'Could not load AI opponents.');
    }

    try {
      setCards(loadCards());
    } catch (err) {
      setCards([]);
      nextErrors.push(err instanceof Error ? err.message : 'Could not load cards.');
    }

    setForm((current) => ({
      ...current,
      savedDeckId:
        loadedDecks.some((deck) => deck.id === current.savedDeckId)
          ? current.savedDeckId
          : loadedDecks[0]?.id ?? '',
    }));
    if (nextErrors.length > 0) {
      setError(nextErrors[0]!);
      setSuccess(null);
    } else {
      setError(null);
    }
  }, []);

  useEffect(() => {
    refresh();
  }, [refresh]);

  function clearMessages() {
    setError(null);
    setSuccess(null);
  }

  function resetForm() {
    setEditingId(null);
    setForm(createEmptyForm(decks[0]?.id ?? ''));
  }

  function buildDraftOpponent(): AiOpponent {
    return {
      id: editingId ?? 'draft-preview',
      name: form.name,
      portraitImageUrl: form.portraitImageUrl || undefined,
      difficulty: form.difficulty,
      playStyle: form.playStyle,
      deckSource: form.deckSource,
      savedDeckId: form.savedDeckId || undefined,
      includeLegendary: form.includeLegendary,
      preferredCreatureType: form.preferredCreatureType || undefined,
      catchphrase: form.catchphrase || undefined,
    };
  }

  function previewResolvedDeck(opponent: AiOpponent) {
    const validationErrors = validateAiOpponent(opponent);
    if (validationErrors.length > 0) {
      throw new Error(validationErrors[0]);
    }
    const deck = resolveAiOpponentDeck(opponent, decks, cards);
    setPreviewOpponent(opponent);
    setPreviewDeck(deck);
  }

  function handlePreviewDraft() {
    clearMessages();
    try {
      previewResolvedDeck(buildDraftOpponent());
    } catch (err) {
      setPreviewDeck(null);
      setPreviewOpponent(null);
      setError(err instanceof Error ? err.message : 'Could not preview opponent deck.');
    }
  }

  function handleSave() {
    clearMessages();
    try {
      if (editingId) {
        const next: AiOpponent = {
          id: editingId,
          name: form.name,
          portraitImageUrl: form.portraitImageUrl || undefined,
          difficulty: form.difficulty,
          playStyle: form.playStyle,
          deckSource: form.deckSource,
          savedDeckId: form.savedDeckId || undefined,
          includeLegendary: form.includeLegendary,
          preferredCreatureType: form.preferredCreatureType || undefined,
          catchphrase: form.catchphrase || undefined,
        };
        updateAiOpponent(next);
        setSuccess(`Updated "${next.name.trim()}".`);
        if (previewOpponent?.id === next.id) {
          previewResolvedDeck(next);
        }
      } else {
        const created = createAiOpponent({
          name: form.name,
          portraitImageUrl: form.portraitImageUrl || undefined,
          difficulty: form.difficulty,
          playStyle: form.playStyle,
          deckSource: form.deckSource,
          savedDeckId: form.savedDeckId || undefined,
          includeLegendary: form.includeLegendary,
          preferredCreatureType: form.preferredCreatureType || undefined,
          catchphrase: form.catchphrase || undefined,
        });
        saveAiOpponent(created);
        setSuccess(`Created "${created.name}".`);
      }
      refresh();
      resetForm();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not save AI opponent.');
    }
  }

  function handleEdit(opponent: AiOpponent) {
    setEditingId(opponent.id);
    setForm({
      name: opponent.name,
      portraitImageUrl: opponent.portraitImageUrl ?? '',
      difficulty: opponent.difficulty,
      playStyle: opponent.playStyle,
      deckSource: opponent.deckSource,
      savedDeckId: opponent.savedDeckId ?? decks[0]?.id ?? '',
      includeLegendary: opponent.includeLegendary,
      preferredCreatureType: opponent.preferredCreatureType ?? '',
      catchphrase: opponent.catchphrase ?? '',
    });
    clearMessages();
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  function handleDelete(opponent: AiOpponent) {
    if (!window.confirm(`Delete AI opponent "${opponent.name}"?`)) return;
    try {
      deleteAiOpponent(opponent.id);
      if (editingId === opponent.id) {
        resetForm();
      }
      if (previewOpponent?.id === opponent.id) {
        setPreviewOpponent(null);
        setPreviewDeck(null);
      }
      refresh();
      setSuccess(`Deleted "${opponent.name}".`);
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not delete AI opponent.');
    }
  }

  return (
    <div className="page ai-opponents-page">
      <div className="page__header-row">
        <div>
          <h1>AI Opponents</h1>
          <p className="page__subtitle">
            Build reusable AI profiles with saved decks or auto-generated deck settings.
          </p>
        </div>
      </div>

      <section className="ai-opponents-form">
        <h2>{editingId ? 'Edit AI Opponent' : 'Create AI Opponent'}</h2>
        <div className="ai-opponents-form__grid">
          <label>
            Name
            <input
              type="text"
              value={form.name}
              onChange={(e) => {
                clearMessages();
                setForm((current) => ({ ...current, name: e.target.value }));
              }}
              placeholder="Goblin Coach"
            />
          </label>
          <label>
            Portrait image URL
            <input
              type="text"
              value={form.portraitImageUrl}
              onChange={(e) => {
                clearMessages();
                setForm((current) => ({ ...current, portraitImageUrl: e.target.value }));
              }}
              placeholder="https://... or data:image/..."
            />
          </label>
          <label>
            Difficulty
            <select
              value={form.difficulty}
              onChange={(e) => {
                clearMessages();
                setForm((current) => ({
                  ...current,
                  difficulty: e.target.value as AutoDeckDifficulty,
                }));
              }}
            >
              {AUTO_DIFFICULTIES.map((difficulty) => (
                <option key={difficulty} value={difficulty}>
                  {difficulty[0]?.toUpperCase()}
                  {difficulty.slice(1)}
                </option>
              ))}
            </select>
          </label>
          <label>
            Play style
            <select
              value={form.playStyle}
              onChange={(e) => {
                clearMessages();
                setForm((current) => ({
                  ...current,
                  playStyle: e.target.value as AutoDeckStyle,
                }));
              }}
            >
              {AUTO_STYLES.map((style) => (
                <option key={style} value={style}>
                  {labelAutoStyle(style)}
                </option>
              ))}
            </select>
          </label>
          <label>
            Deck source
            <select
              value={form.deckSource}
              onChange={(e) => {
                clearMessages();
                setForm((current) => ({
                  ...current,
                  deckSource: e.target.value as AiOpponentDeckSource,
                }));
              }}
            >
              <option value="autoGenerated">Auto Generated</option>
              <option value="savedDeck">Saved Deck</option>
            </select>
          </label>
          {form.deckSource === 'savedDeck' ? (
            <label>
              Saved deck
              <select
                value={form.savedDeckId}
                onChange={(e) => {
                  clearMessages();
                  setForm((current) => ({ ...current, savedDeckId: e.target.value }));
                }}
              >
                {decks.length === 0 ? (
                  <option value="">No saved decks available</option>
                ) : (
                  decks.map((deck) => (
                    <option key={deck.id} value={deck.id}>
                      {deck.name}
                    </option>
                  ))
                )}
              </select>
            </label>
          ) : (
            <>
              <label className="ai-opponents-form__checkbox">
                <span>Include Legendary cards?</span>
                <input
                  type="checkbox"
                  checked={form.includeLegendary}
                  onChange={(e) => {
                    clearMessages();
                    setForm((current) => ({
                      ...current,
                      includeLegendary: e.target.checked,
                    }));
                  }}
                />
              </label>
              <label>
                Preferred creature type
                <select
                  value={form.preferredCreatureType}
                  onChange={(e) => {
                    clearMessages();
                    setForm((current) => ({
                      ...current,
                      preferredCreatureType: e.target.value,
                    }));
                  }}
                >
                  <option value="">Any</option>
                  {COMMON_CREATURE_TYPES.map((type) => (
                    <option key={type} value={type}>
                      {type}
                    </option>
                  ))}
                </select>
              </label>
            </>
          )}
          <label className="ai-opponents-form__wide">
            Catchphrase
            <input
              type="text"
              value={form.catchphrase}
              onChange={(e) => {
                clearMessages();
                setForm((current) => ({ ...current, catchphrase: e.target.value }));
              }}
              placeholder="Prepare to be outplayed!"
            />
          </label>
        </div>
        <div className="ai-opponents-form__actions">
          <button type="button" onClick={handlePreviewDraft}>
            Preview Opponent Deck
          </button>
          <button type="button" className="ai-opponents-form__save" onClick={handleSave}>
            {editingId ? 'Update AI Opponent' : 'Create AI Opponent'}
          </button>
          {editingId && (
            <button
              type="button"
              className="ai-opponents-form__cancel"
              onClick={() => {
                clearMessages();
                resetForm();
              }}
            >
              Cancel Edit
            </button>
          )}
        </div>
      </section>

      {previewDeck && previewOpponent && (
        <section className="ai-opponents-preview">
          <div className="ai-opponents-preview__header">
            <div className="ai-opponents-preview__identity">
              {previewOpponent.portraitImageUrl && (
                <img
                  src={previewOpponent.portraitImageUrl}
                  alt={`${previewOpponent.name} portrait`}
                  className="ai-opponents-preview__portrait"
                />
              )}
              <div>
                <h2>{previewOpponent.name}</h2>
                <p>
                  {previewOpponent.difficulty[0]?.toUpperCase()}
                  {previewOpponent.difficulty.slice(1)} /{' '}
                  {labelAutoStyle(previewOpponent.playStyle)} /{' '}
                  {labelDeckSource(previewOpponent.deckSource)}
                  {previewOpponent.preferredCreatureType
                    ? ` / ${previewOpponent.preferredCreatureType}`
                    : ''}
                </p>
                {previewOpponent.catchphrase && (
                  <blockquote>{previewOpponent.catchphrase}</blockquote>
                )}
              </div>
            </div>
            <strong>{previewDeck.entries.reduce((sum, entry) => sum + entry.count, 0)} cards</strong>
          </div>
          <ul className="ai-opponents-preview__list" role="list">
            {previewDeck.entries.map((entry) => {
              const card = cardsById.get(entry.cardId);
              if (!card) {
                return (
                  <li key={entry.cardId} className="ai-opponents-preview__row">
                    <span>Missing card: {entry.cardId} ×{entry.count}</span>
                    <span className="ai-opponents-preview__meta">This saved reference no longer exists.</span>
                  </li>
                );
              }
              return (
                <li key={entry.cardId} className="ai-opponents-preview__row">
                  <span>
                    {card.name} ×{entry.count}
                  </span>
                  <span className="ai-opponents-preview__meta">
                    Cost {card.cost} / {card.attack} ATK / {card.health} HP
                  </span>
                </li>
              );
            })}
          </ul>
        </section>
      )}

      <section className="ai-opponents-list">
        <h2>Saved AI Opponents ({opponents.length})</h2>
        {opponents.length === 0 ? (
          <p className="ai-opponents-list__empty">No AI opponents yet.</p>
        ) : (
          <ul className="ai-opponents-list__items" role="list">
            {opponents.map((opponent) => (
              <li key={opponent.id} className="ai-opponents-list__row">
                <div>
                  <strong>{opponent.name}</strong>
                  <p>
                    {opponent.difficulty[0]?.toUpperCase()}
                    {opponent.difficulty.slice(1)} / {labelAutoStyle(opponent.playStyle)} /{' '}
                    {labelDeckSource(opponent.deckSource)}
                    {opponent.preferredCreatureType ? ` / ${opponent.preferredCreatureType}` : ''}
                  </p>
                </div>
                <div className="ai-opponents-list__actions">
                  <button
                    type="button"
                    onClick={() => {
                      clearMessages();
                      try {
                        previewResolvedDeck(opponent);
                      } catch (err) {
                        setPreviewDeck(null);
                        setPreviewOpponent(null);
                        setError(err instanceof Error ? err.message : 'Could not preview opponent deck.');
                      }
                    }}
                  >
                    Preview Deck
                  </button>
                  <button type="button" onClick={() => handleEdit(opponent)}>
                    Edit
                  </button>
                  <button
                    type="button"
                    className="ai-opponents-list__delete"
                    onClick={() => handleDelete(opponent)}
                  >
                    Delete
                  </button>
                </div>
              </li>
            ))}
          </ul>
        )}
      </section>

      {success && <p className="play-success">{success}</p>}
      {error && <p className="play-error">{error}</p>}
    </div>
  );
}
