import { useCallback, useEffect, useRef, useState } from 'react';
import type { Deck } from '../models/deck';
import { loadDecks } from '../storage/deckStorage';
import { loadCards } from '../storage/cardStorage';
import { loadAiOpponents } from '../storage/aiOpponentStorage';
import { isAiTurn, runAiTurn } from '../engine/ai';
import { GameBoard } from '../components/GameBoard';
import {
  advanceTournament,
  createTournament,
  deleteTournament,
  loadTournaments,
  restartCurrentRound,
  saveTournament,
  updateTournamentGame,
  type TournamentDifficultyCurve,
  type TournamentOpponentSource,
  type TournamentProgress,
  type TournamentRoundCount,
} from '../storage/tournamentStorage';
import './TournamentsPage.css';

const ROUND_OPTIONS: TournamentRoundCount[] = [3, 5, 8];
const CURVE_OPTIONS: TournamentDifficultyCurve[] = ['easy', 'normal', 'hard', 'rising'];

interface TournamentSetupState {
  name: string;
  playerDeckId: string;
  totalRounds: TournamentRoundCount;
  difficultyCurve: TournamentDifficultyCurve;
  opponentSource: TournamentOpponentSource;
}

function createDefaultSetup(playerDeckId = ''): TournamentSetupState {
  return {
    name: 'Monster Cup',
    playerDeckId,
    totalRounds: 3,
    difficultyCurve: 'normal',
    opponentSource: 'autoGenerated',
  };
}

function labelCurve(curve: TournamentDifficultyCurve): string {
  switch (curve) {
    case 'easy':
      return 'Easy';
    case 'normal':
      return 'Normal';
    case 'hard':
      return 'Hard';
    case 'rising':
      return 'Rising Difficulty';
  }
}

function labelDifficulty(difficulty: 'easy' | 'normal' | 'hard'): string {
  return difficulty[0].toUpperCase() + difficulty.slice(1);
}

function labelSource(source: TournamentOpponentSource): string {
  return source === 'existingOpponents' ? 'Use existing AI opponents' : 'Auto-generate opponents';
}

function isFinishedGame(tournament: TournamentProgress | null): boolean {
  const game = tournament?.currentGame;
  if (!game) return false;
  return game.winner !== null || (game.players[0].health <= 0 && game.players[1].health <= 0);
}

export function TournamentsPage() {
  const [decks, setDecks] = useState<Deck[]>([]);
  const [cardsCount, setCardsCount] = useState(0);
  const [tournaments, setTournaments] = useState<TournamentProgress[]>([]);
  const [setup, setSetup] = useState<TournamentSetupState>(createDefaultSetup());
  const [activeTournament, setActiveTournament] = useState<TournamentProgress | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [aiThinking, setAiThinking] = useState(false);
  const aiRunningRef = useRef(false);

  const refresh = useCallback(() => {
    const loadedDecks = loadDecks();
    const loadedCards = loadCards();
    const loadedTournaments = loadTournaments();

    setDecks(loadedDecks);
    setCardsCount(loadedCards.length);
    setTournaments(loadedTournaments);
    setSetup((current) => ({
      ...current,
      playerDeckId:
        loadedDecks.some((deck) => deck.id === current.playerDeckId)
          ? current.playerDeckId
          : loadedDecks[0]?.id ?? '',
    }));
    setActiveTournament((current) => {
      if (!current) return null;
      return loadedTournaments.find((tournament) => tournament.id === current.id) ?? current;
    });
  }, []);

  useEffect(() => {
    refresh();
  }, [refresh]);

  useEffect(() => {
    if (!activeTournament || activeTournament.status !== 'in_progress' || !activeTournament.currentGame) {
      setAiThinking(false);
      aiRunningRef.current = false;
      return;
    }
    if (!isAiTurn(activeTournament.currentGame)) {
      setAiThinking(false);
      aiRunningRef.current = false;
      return;
    }
    if (aiRunningRef.current) return;

    aiRunningRef.current = true;
    setAiThinking(true);

    const timer = window.setTimeout(() => {
      try {
        const next = updateTournamentGame(
          activeTournament,
          runAiTurn(activeTournament.currentGame!),
        );
        saveTournament(next);
        setActiveTournament(next);
        setError(null);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'AI turn failed.');
      } finally {
        setAiThinking(false);
        aiRunningRef.current = false;
      }
    }, 700);

    return () => window.clearTimeout(timer);
  }, [activeTournament]);

  function clearMessages() {
    setError(null);
    setSuccess(null);
  }

  function handleStartTournament() {
    clearMessages();
    const playerDeck = decks.find((deck) => deck.id === setup.playerDeckId);
    if (!playerDeck) {
      setError('Please choose a saved deck for the tournament.');
      return;
    }

    try {
      const tournament = createTournament({
        name: setup.name,
        playerDeck,
        totalRounds: setup.totalRounds,
        difficultyCurve: setup.difficultyCurve,
        opponentSource: setup.opponentSource,
        cards: loadCards(),
        aiOpponents: loadAiOpponents(),
        decks: loadDecks(),
      });
      saveTournament(tournament);
      setActiveTournament(tournament);
      setSuccess(`Started "${tournament.name}".`);
      refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not start tournament.');
    }
  }

  function handleSelectTournament(tournament: TournamentProgress) {
    clearMessages();
    setActiveTournament(tournament);
  }

  function handleSaveAndExit() {
    if (activeTournament) {
      saveTournament(activeTournament);
      setSuccess(`Saved progress for "${activeTournament.name}".`);
    }
    setActiveTournament(null);
    refresh();
  }

  function handleDeleteTournament(tournament: TournamentProgress) {
    if (!window.confirm(`Delete tournament "${tournament.name}"?`)) return;
    try {
      deleteTournament(tournament.id);
      if (activeTournament?.id === tournament.id) {
        setActiveTournament(null);
      }
      refresh();
      setSuccess(`Deleted "${tournament.name}".`);
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not delete tournament.');
    }
  }

  function handleAdvanceTournament() {
    if (!activeTournament) return;
    clearMessages();
    try {
      const next = advanceTournament(activeTournament, loadCards());
      saveTournament(next);
      setActiveTournament(next);
      refresh();
      if (next.status === 'won') {
        setSuccess(`You won "${next.name}"!`);
      } else if (next.status === 'lost') {
        setSuccess(`"${next.name}" has ended.`);
      } else {
        setSuccess(`Advanced to round ${next.currentRoundIndex + 1}.`);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not advance tournament.');
    }
  }

  function handleReplayRound() {
    if (!activeTournament) return;
    clearMessages();
    try {
      const next = restartCurrentRound(activeTournament, loadCards());
      saveTournament(next);
      setActiveTournament(next);
      refresh();
      setSuccess(`Replaying round ${next.currentRoundIndex + 1}.`);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not replay this round.');
    }
  }

  const currentRound = activeTournament
    ? activeTournament.rounds[activeTournament.currentRoundIndex] ?? null
    : null;
  const finishedGame = isFinishedGame(activeTournament);
  const playerWonBattle = activeTournament?.currentGame?.winner === 0;
  const battleDraw = Boolean(
    finishedGame &&
      activeTournament?.currentGame?.winner === null &&
      activeTournament.currentGame.players[0].health <= 0 &&
      activeTournament.currentGame.players[1].health <= 0,
  );
  const wins = activeTournament?.rounds.filter((round) => round.result === 'won').length ?? 0;

  if (activeTournament) {
    return (
      <div className="page tournaments-page">
        <div className="tournament-active">
          <div className="tournament-active__header">
            <div>
              <h1>{activeTournament.name}</h1>
              <p className="page__subtitle">
                Round {activeTournament.currentRoundIndex + 1} of {activeTournament.totalRounds} ·{' '}
                {wins} win{wins === 1 ? '' : 's'}
              </p>
            </div>
            <div className="tournament-active__actions">
              <button type="button" onClick={handleSaveAndExit}>
                Save and Exit
              </button>
              <button
                type="button"
                className="tournament-active__danger"
                onClick={() => handleDeleteTournament(activeTournament)}
              >
                Delete Tournament
              </button>
            </div>
          </div>

          {activeTournament.status === 'in_progress' && currentRound && activeTournament.currentGame ? (
            <>
              <section className="tournament-summary">
                <h2>Current Opponent</h2>
                <p>
                  <strong>{currentRound.opponent.name}</strong> · {labelDifficulty(currentRound.opponent.difficulty)} ·{' '}
                  {currentRound.opponent.playStyle}
                  {currentRound.opponent.preferredCreatureType
                    ? ` · ${currentRound.opponent.preferredCreatureType}`
                    : ''}
                </p>
                {currentRound.opponent.catchphrase && (
                  <blockquote>{currentRound.opponent.catchphrase}</blockquote>
                )}
              </section>

              {aiThinking && <p className="play-ai-thinking">AI is thinking…</p>}

              <GameBoard
                game={activeTournament.currentGame}
                gameMode="ai"
                hideGameOverScreen
                onGameChange={(state) => {
                  const next = updateTournamentGame(activeTournament, state);
                  saveTournament(next);
                  setActiveTournament(next);
                  setSuccess(null);
                }}
                inputDisabled={aiThinking || isAiTurn(activeTournament.currentGame)}
                onNewGame={() => {}}
                onLoadGame={() => {}}
                onReturnToMenu={() => {}}
              />

              {finishedGame && (
                <section className="tournament-result">
                  <h2>
                    {battleDraw
                      ? 'Round Draw'
                      : playerWonBattle
                        ? 'Round Cleared'
                        : 'Tournament Defeat'}
                  </h2>
                  <p>
                    {battleDraw
                      ? 'Both players reached 0 health. Replay this round to continue.'
                      : playerWonBattle
                        ? activeTournament.currentRoundIndex === activeTournament.totalRounds - 1
                          ? 'You defeated the final opponent. Finish the tournament to see your results.'
                          : 'You won this round. Advance when you are ready.'
                        : 'You lost this round. Record the loss to see the final results.'}
                  </p>
                  <div className="tournament-result__actions">
                    {battleDraw ? (
                      <button type="button" onClick={handleReplayRound}>
                        Replay Round
                      </button>
                    ) : (
                      <button type="button" onClick={handleAdvanceTournament}>
                        {playerWonBattle
                          ? activeTournament.currentRoundIndex === activeTournament.totalRounds - 1
                            ? 'Finish Tournament'
                            : `Advance to Round ${activeTournament.currentRoundIndex + 2}`
                          : 'View Tournament Results'}
                      </button>
                    )}
                  </div>
                </section>
              )}
            </>
          ) : (
            <section className="tournament-result">
              <h2>{activeTournament.status === 'won' ? 'Tournament Victory!' : 'Tournament Over'}</h2>
              <p>
                {activeTournament.status === 'won'
                  ? `You cleared all ${activeTournament.totalRounds} rounds.`
                  : `You reached round ${activeTournament.currentRoundIndex + 1} before being defeated.`}
              </p>
              <ul className="tournament-result__rounds" role="list">
                {activeTournament.rounds.map((round) => (
                  <li key={round.roundNumber} className="tournament-result__round">
                    <span>
                      Round {round.roundNumber}: {round.opponent.name}
                      {round.opponent.preferredCreatureType
                        ? ` (${round.opponent.preferredCreatureType})`
                        : ''}
                    </span>
                    <strong>{round.result.toUpperCase()}</strong>
                  </li>
                ))}
              </ul>
              <div className="tournament-result__actions">
                <button type="button" onClick={handleSaveAndExit}>
                  Back to Tournaments
                </button>
                <button
                  type="button"
                  className="tournament-active__danger"
                  onClick={() => handleDeleteTournament(activeTournament)}
                >
                  Delete Tournament
                </button>
              </div>
            </section>
          )}

          {success && <p className="play-success">{success}</p>}
          {error && <p className="play-error">{error}</p>}
        </div>
      </div>
    );
  }

  return (
    <div className="page tournaments-page">
      <div className="page__header-row">
        <div>
          <h1>Tournaments</h1>
          <p className="page__subtitle">Fight through a series of AI battles with one saved deck.</p>
        </div>
      </div>

      {tournaments.length > 0 && (
        <section className="tournament-saves">
          <h2>Saved Tournaments</h2>
          <ul className="tournament-saves__list" role="list">
            {tournaments.map((tournament) => {
              const tournamentWins = tournament.rounds.filter((round) => round.result === 'won').length;
              return (
                <li key={tournament.id} className="tournament-saves__row">
                  <div>
                    <strong>{tournament.name}</strong>
                    <p>
                      {tournament.status === 'in_progress'
                        ? `Round ${tournament.currentRoundIndex + 1} of ${tournament.totalRounds}`
                        : tournament.status === 'won'
                          ? 'Completed - Victory'
                          : 'Completed - Defeat'}{' '}
                      · {tournamentWins} win{tournamentWins === 1 ? '' : 's'}
                    </p>
                  </div>
                  <div className="tournament-saves__actions">
                    <button type="button" onClick={() => handleSelectTournament(tournament)}>
                      {tournament.status === 'in_progress' ? 'Continue' : 'View'}
                    </button>
                    <button
                      type="button"
                      className="tournament-active__danger"
                      onClick={() => handleDeleteTournament(tournament)}
                    >
                      Delete
                    </button>
                  </div>
                </li>
              );
            })}
          </ul>
        </section>
      )}

      <section className="tournament-setup">
        <h2>Start a Tournament</h2>
        {decks.length === 0 ? (
          <p className="play-error">Create and save a deck first.</p>
        ) : (
          <>
            <div className="tournament-setup__grid">
              <label>
                Tournament name
                <input
                  type="text"
                  value={setup.name}
                  onChange={(e) => {
                    clearMessages();
                    setSetup((current) => ({ ...current, name: e.target.value }));
                  }}
                />
              </label>
              <label>
                Player deck
                <select
                  value={setup.playerDeckId}
                  onChange={(e) => {
                    clearMessages();
                    setSetup((current) => ({ ...current, playerDeckId: e.target.value }));
                  }}
                >
                  {decks.map((deck) => (
                    <option key={deck.id} value={deck.id}>
                      {deck.name}
                    </option>
                  ))}
                </select>
              </label>
              <label>
                Number of rounds
                <select
                  value={setup.totalRounds}
                  onChange={(e) => {
                    clearMessages();
                    setSetup((current) => ({
                      ...current,
                      totalRounds: Number(e.target.value) as TournamentRoundCount,
                    }));
                  }}
                >
                  {ROUND_OPTIONS.map((rounds) => (
                    <option key={rounds} value={rounds}>
                      {rounds}
                    </option>
                  ))}
                </select>
              </label>
              <label>
                Difficulty curve
                <select
                  value={setup.difficultyCurve}
                  onChange={(e) => {
                    clearMessages();
                    setSetup((current) => ({
                      ...current,
                      difficultyCurve: e.target.value as TournamentDifficultyCurve,
                    }));
                  }}
                >
                  {CURVE_OPTIONS.map((curve) => (
                    <option key={curve} value={curve}>
                      {labelCurve(curve)}
                    </option>
                  ))}
                </select>
              </label>
              <label>
                Opponent source
                <select
                  value={setup.opponentSource}
                  onChange={(e) => {
                    clearMessages();
                    setSetup((current) => ({
                      ...current,
                      opponentSource: e.target.value as TournamentOpponentSource,
                    }));
                  }}
                >
                  <option value="existingOpponents">Use existing AI opponents</option>
                  <option value="autoGenerated">Auto-generate opponents</option>
                </select>
              </label>
            </div>

            <div className="tournament-setup__notes">
              <p>Saved decks: {decks.length}</p>
              <p>Cards in library: {cardsCount}</p>
              <p>AI opponents: {loadAiOpponents().length}</p>
              <p>Opponent source: {labelSource(setup.opponentSource)}</p>
            </div>

            {setup.opponentSource === 'existingOpponents' &&
              loadAiOpponents().length < setup.totalRounds && (
                <p className="play-error">
                  You need at least {setup.totalRounds} AI opponents saved for this tournament setup.
                </p>
              )}

            <button type="button" className="tournament-setup__start" onClick={handleStartTournament}>
              Start Tournament
            </button>
          </>
        )}
      </section>

      {success && <p className="play-success">{success}</p>}
      {error && <p className="play-error">{error}</p>}
    </div>
  );
}
