import { beforeEach, describe, expect, it, vi } from 'vitest';
import { cardWithId } from '../models/card';
import type { Deck } from '../models/deck';
import {
  createAiOpponent,
  deleteAiOpponent,
  loadAiOpponents,
  resolveAiOpponentDeck,
  saveAiOpponent,
  updateAiOpponent,
} from './aiOpponentStorage';

const cards = [
  cardWithId('mouse', {
    name: 'Mouse',
    imageUrl: 'data:image/webp;base64,mouse',
    cost: 1,
    attack: 1,
    health: 1,
    flavorText: 'Tiny.',
    rarity: 'common',
  }),
  cardWithId('shield', {
    name: 'Shield Bug',
    imageUrl: 'data:image/webp;base64,shield',
    cost: 2,
    attack: 1,
    health: 5,
    flavorText: 'Tough.',
    rarity: 'common',
  }),
  cardWithId('claw', {
    name: 'Claw Cub',
    imageUrl: 'data:image/webp;base64,claw',
    cost: 2,
    attack: 4,
    health: 2,
    flavorText: 'Quick.',
    rarity: 'rare',
  }),
  cardWithId('brute', {
    name: 'Brute',
    imageUrl: 'data:image/webp;base64,brute',
    cost: 5,
    attack: 6,
    health: 5,
    flavorText: 'Big.',
    rarity: 'common',
  }),
  cardWithId('guardian', {
    name: 'Guardian',
    imageUrl: 'data:image/webp;base64,guardian',
    cost: 4,
    attack: 2,
    health: 7,
    flavorText: 'Wall.',
    rarity: 'rare',
  }),
  cardWithId('ogre', {
    name: 'Ogre',
    imageUrl: 'data:image/webp;base64,ogre',
    cost: 6,
    attack: 7,
    health: 7,
    flavorText: 'Heavy.',
    rarity: 'rare',
  }),
  cardWithId('hydra', {
    name: 'Hydra',
    imageUrl: 'data:image/webp;base64,hydra',
    cost: 7,
    attack: 8,
    health: 8,
    flavorText: 'Legend.',
    rarity: 'legendary',
  }),
  cardWithId('sparrow', {
    name: 'Sparrow',
    imageUrl: 'data:image/webp;base64,sparrow',
    cost: 1,
    attack: 2,
    health: 1,
    flavorText: 'Fast.',
    rarity: 'common',
  }),
  cardWithId('knight', {
    name: 'Knight',
    imageUrl: 'data:image/webp;base64,knight',
    cost: 4,
    attack: 4,
    health: 4,
    flavorText: 'Solid.',
    rarity: 'rare',
  }),
  cardWithId('colossus', {
    name: 'Colossus',
    imageUrl: 'data:image/webp;base64,colossus',
    cost: 8,
    attack: 9,
    health: 10,
    flavorText: 'Huge.',
    rarity: 'rare',
  }),
  cardWithId('fox', {
    name: 'Fox',
    imageUrl: 'data:image/webp;base64,fox',
    cost: 3,
    attack: 3,
    health: 3,
    flavorText: 'Clever.',
    rarity: 'common',
  }),
];

const savedDeck: Deck = {
  id: 'deck-1',
  name: 'Starter Deck',
  entries: cards.map((card, index) => ({
    cardId: card.id,
    count: index === 0 ? 3 : index < 10 ? 3 : 0,
  })).filter((entry) => entry.count > 0),
};

describe('aiOpponentStorage', () => {
  beforeEach(() => {
    const store = new Map<string, string>();
    vi.stubGlobal('localStorage', {
      getItem: (key: string) => store.get(key) ?? null,
      setItem: (key: string, value: string) => {
        store.set(key, value);
      },
      removeItem: (key: string) => {
        store.delete(key);
      },
      clear: () => store.clear(),
    });
  });

  it('saves and loads opponents', () => {
    const opponent = createAiOpponent({
      name: '  Coach Bot  ',
      difficulty: 'easy',
      playStyle: 'balanced',
      deckSource: 'autoGenerated',
      includeLegendary: false,
      catchphrase: '  Try your best!  ',
    });

    saveAiOpponent(opponent);

    expect(loadAiOpponents()).toEqual([
      {
        ...opponent,
        name: 'Coach Bot',
        catchphrase: 'Try your best!',
      },
    ]);
  });

  it('updates opponents', () => {
    const opponent = createAiOpponent({
      name: 'Trainer',
      difficulty: 'easy',
      playStyle: 'balanced',
      deckSource: 'autoGenerated',
      includeLegendary: false,
    });

    saveAiOpponent(opponent);
    updateAiOpponent({
      ...opponent,
      difficulty: 'hard',
      playStyle: 'aggressive',
      catchphrase: 'No mercy.',
    });

    expect(loadAiOpponents()[0]).toMatchObject({
      id: opponent.id,
      difficulty: 'hard',
      playStyle: 'aggressive',
      catchphrase: 'No mercy.',
    });
  });

  it('deletes opponents', () => {
    const opponent = createAiOpponent({
      name: 'Trainer',
      difficulty: 'easy',
      playStyle: 'balanced',
      deckSource: 'autoGenerated',
      includeLegendary: false,
    });

    saveAiOpponent(opponent);
    deleteAiOpponent(opponent.id);

    expect(loadAiOpponents()).toEqual([]);
  });

  it('requires a saved deck id for saved deck opponents', () => {
    expect(() =>
      createAiOpponent({
        name: 'Deck Bot',
        difficulty: 'normal',
        playStyle: 'random',
        deckSource: 'savedDeck',
        includeLegendary: true,
      }),
    ).toThrow(/saved deck/i);
  });

  it('resolves a saved deck opponent to its assigned deck', () => {
    const opponent = createAiOpponent({
      name: 'Deck Bot',
      difficulty: 'normal',
      playStyle: 'random',
      deckSource: 'savedDeck',
      savedDeckId: savedDeck.id,
      includeLegendary: true,
    });

    const resolved = resolveAiOpponentDeck(opponent, [savedDeck], cards);

    expect(resolved).toBe(savedDeck);
  });

  it('resolves an auto-generated opponent to a legal deck', () => {
    const opponent = createAiOpponent({
      name: 'Swarm Queen',
      difficulty: 'hard',
      playStyle: 'cheap-swarm',
      deckSource: 'autoGenerated',
      includeLegendary: false,
    });

    const resolved = resolveAiOpponentDeck(opponent, [savedDeck], cards);
    const total = resolved.entries.reduce((sum, entry) => sum + entry.count, 0);

    expect(resolved.name).toBe('Swarm Queen Deck');
    expect(total).toBe(30);
    expect(
      resolved.entries.every((entry) => {
        const card = cards.find((candidate) => candidate.id === entry.cardId)!;
        return card.rarity !== 'legendary';
      }),
    ).toBe(true);
  });
});
