import type { Card } from '../models/card';
import type { Deck } from '../models/deck';
import { generateAutoDeck, type AutoDeckDifficulty, type AutoDeckStyle } from '../engine/autoDeckBuilder';
import { readStoredJson, writeStoredJson } from './localStorageSafety';

const STORAGE_KEY = 'battle-monsters:ai-opponents';

export type AiOpponentDeckSource = 'savedDeck' | 'autoGenerated';

export interface AiOpponent {
  id: string;
  name: string;
  portraitImageUrl?: string;
  difficulty: AutoDeckDifficulty;
  playStyle: AutoDeckStyle;
  deckSource: AiOpponentDeckSource;
  savedDeckId?: string;
  includeLegendary: boolean;
  preferredCreatureType?: string;
  catchphrase?: string;
}

export type NewAiOpponent = Omit<AiOpponent, 'id'>;

function isDifficulty(value: unknown): value is AutoDeckDifficulty {
  return value === 'easy' || value === 'normal' || value === 'hard';
}

function isPlayStyle(value: unknown): value is AutoDeckStyle {
  return (
    value === 'random' ||
    value === 'balanced' ||
    value === 'aggressive' ||
    value === 'defensive' ||
    value === 'big-monsters' ||
    value === 'cheap-swarm'
  );
}

function isDeckSource(value: unknown): value is AiOpponentDeckSource {
  return value === 'savedDeck' || value === 'autoGenerated';
}

function normalizeOptionalText(value: string | undefined): string | undefined {
  const trimmed = value?.trim() ?? '';
  return trimmed ? trimmed : undefined;
}

function normalizeAiOpponent(input: AiOpponent): AiOpponent {
  return {
    ...input,
    name: input.name.trim(),
    portraitImageUrl: normalizeOptionalText(input.portraitImageUrl),
    savedDeckId: normalizeOptionalText(input.savedDeckId),
    preferredCreatureType: normalizeOptionalText(input.preferredCreatureType),
    catchphrase: normalizeOptionalText(input.catchphrase),
  };
}

export function validateAiOpponent(input: NewAiOpponent | AiOpponent): string[] {
  const normalized = {
    ...input,
    name: input.name.trim(),
    savedDeckId: normalizeOptionalText(input.savedDeckId),
  };
  const errors: string[] = [];

  if (!normalized.name) {
    errors.push('AI opponent name is required.');
  }
  if (!isDifficulty(normalized.difficulty)) {
    errors.push('AI opponent difficulty is invalid.');
  }
  if (!isPlayStyle(normalized.playStyle)) {
    errors.push('AI opponent play style is invalid.');
  }
  if (!isDeckSource(normalized.deckSource)) {
    errors.push('AI opponent deck source is invalid.');
  }
  if (normalized.deckSource === 'savedDeck' && !normalized.savedDeckId) {
    errors.push('Saved deck AI opponents must choose a saved deck.');
  }

  return errors;
}

export function createAiOpponent(input: NewAiOpponent): AiOpponent {
  const opponent: AiOpponent = normalizeAiOpponent({
    id: crypto.randomUUID(),
    ...input,
  });
  const errors = validateAiOpponent(opponent);
  if (errors.length > 0) {
    throw new Error(errors.join(' '));
  }
  return opponent;
}

export function isAiOpponent(value: unknown): value is AiOpponent {
  if (!value || typeof value !== 'object') return false;
  const v = value as Record<string, unknown>;
  return (
    typeof v.id === 'string' &&
    typeof v.name === 'string' &&
    (typeof v.portraitImageUrl === 'string' || typeof v.portraitImageUrl === 'undefined') &&
    isDifficulty(v.difficulty) &&
    isPlayStyle(v.playStyle) &&
    isDeckSource(v.deckSource) &&
    (typeof v.savedDeckId === 'string' || typeof v.savedDeckId === 'undefined') &&
    typeof v.includeLegendary === 'boolean' &&
    (typeof v.preferredCreatureType === 'string' ||
      typeof v.preferredCreatureType === 'undefined') &&
    (typeof v.catchphrase === 'string' || typeof v.catchphrase === 'undefined')
  );
}

export function parseStoredAiOpponents(value: unknown): AiOpponent[] {
  if (!Array.isArray(value)) {
    throw new Error('Expected an AI opponent array.');
  }
  return value.map((item, index) => {
    if (!isAiOpponent(item)) {
      throw new Error(`AI opponent ${index + 1} is invalid.`);
    }
    const normalized = normalizeAiOpponent(item);
    const validationErrors = validateAiOpponent(normalized);
    if (validationErrors.length > 0) {
      throw new Error(`AI opponent "${normalized.name || normalized.id}" is invalid: ${validationErrors[0]}`);
    }
    return normalized;
  });
}

function readRaw(): AiOpponent[] {
  return readStoredJson({
    storageKey: STORAGE_KEY,
    entityName: 'AI opponents',
    createEmpty: () => [],
    parse: parseStoredAiOpponents,
  });
}

function writeAll(opponents: AiOpponent[]): void {
  writeStoredJson(STORAGE_KEY, opponents, 'AI opponents');
}

export function loadAiOpponents(): AiOpponent[] {
  return readRaw();
}

export function getAiOpponentById(id: string): AiOpponent | undefined {
  return readRaw().find((opponent) => opponent.id === id);
}

export function saveAiOpponent(opponent: AiOpponent): void {
  const normalized = normalizeAiOpponent(opponent);
  const errors = validateAiOpponent(normalized);
  if (errors.length > 0) {
    throw new Error(errors.join(' '));
  }
  const opponents = readRaw();
  if (opponents.some((existing) => existing.id === normalized.id)) {
    throw new Error(`AI opponent with id "${normalized.id}" already exists.`);
  }
  opponents.push(normalized);
  writeAll(opponents);
}

export function updateAiOpponent(opponent: AiOpponent): void {
  const normalized = normalizeAiOpponent(opponent);
  const errors = validateAiOpponent(normalized);
  if (errors.length > 0) {
    throw new Error(errors.join(' '));
  }
  const opponents = readRaw();
  const index = opponents.findIndex((existing) => existing.id === normalized.id);
  if (index === -1) {
    throw new Error(`AI opponent with id "${normalized.id}" not found.`);
  }
  opponents[index] = normalized;
  writeAll(opponents);
}

export function deleteAiOpponent(id: string): void {
  const opponents = readRaw();
  const next = opponents.filter((opponent) => opponent.id !== id);
  if (next.length === opponents.length) {
    throw new Error(`AI opponent with id "${id}" not found.`);
  }
  writeAll(next);
}

export function resolveAiOpponentDeck(
  opponent: AiOpponent,
  decks: Deck[],
  cards: Card[],
): Deck {
  if (opponent.deckSource === 'savedDeck') {
    if (!opponent.savedDeckId) {
      throw new Error(`AI opponent "${opponent.name}" does not have a saved deck selected.`);
    }
    const deck = decks.find((candidate) => candidate.id === opponent.savedDeckId);
    if (!deck) {
      throw new Error(`Saved deck for AI opponent "${opponent.name}" was not found.`);
    }
    return deck;
  }

  const generated = generateAutoDeck({
    name: `${opponent.name} Deck`,
    difficulty: opponent.difficulty,
    style: opponent.playStyle,
    includeLegendary: opponent.includeLegendary,
    preferredCreatureType: opponent.preferredCreatureType,
    cards,
  });

  return {
    id: `ai-opponent:${opponent.id}`,
    name: generated.name,
    entries: generated.entries,
  };
}
