import { beforeEach, describe, expect, it, vi } from 'vitest';
import { DEFAULT_CARD_VISUAL_STYLE, type Card } from '../models/card';
import type { Deck } from '../models/deck';
import { createNewGameFromDecks } from '../engine/rules';
import { createAiOpponent, loadAiOpponents, saveAiOpponent } from './aiOpponentStorage';
import { loadCards, saveCard } from './cardStorage';
import {
  backupAllData,
  parseFullDataBackup,
  restoreFullDataBackup,
  type FullDataBackupFile,
} from './dataBackup';
import { loadDecks, saveDeck } from './deckStorage';
import { loadAllSaves, saveGame } from './gameSaveStorage';
import { readAppStorageSnapshot } from './localStorageSafety';
import { loadTournaments, saveTournament, createTournament } from './tournamentStorage';

const CARDS_KEY = 'battle-monsters:cards';
const DECKS_KEY = 'battle-monsters:decks';

function createStorageHarness() {
  const store = new Map<string, string>();
  const failState = {
    key: null as string | null,
    value: null as string | null,
  };

  vi.stubGlobal('localStorage', {
    getItem: (key: string) => store.get(key) ?? null,
    setItem: (key: string, value: string) => {
      if (failState.key === key && failState.value === value) {
        throw new DOMException('Quota exceeded', 'QuotaExceededError');
      }
      store.set(key, value);
    },
    removeItem: (key: string) => {
      store.delete(key);
    },
    clear: () => store.clear(),
  });

  return { store, failState };
}

function makeCard(id: string): Card {
  return {
    id,
    name: `Card ${id}`,
    imageUrl: `data:image/webp;base64,${id}`,
    cost: 1,
    attack: 2,
    health: 3,
    flavorText: `${id} flavor`,
    rarity: 'common',
    creatureTypes: [],
    visualStyle: DEFAULT_CARD_VISUAL_STYLE,
  };
}

function seedBackupableData(prefix: string): FullDataBackupFile {
  const cards = Array.from({ length: 10 }, (_, index) => makeCard(`${prefix}-c${index}`));
  for (const card of cards) {
    saveCard(card);
  }

  const deck: Deck = {
    id: `${prefix}-deck`,
    name: `${prefix} Deck`,
    entries: cards.map((card) => ({ cardId: card.id, count: 3 })),
  };
  saveDeck(deck, cards);

  const opponent = createAiOpponent({
    name: `${prefix} Coach`,
    difficulty: 'normal',
    playStyle: 'balanced',
    deckSource: 'savedDeck',
    savedDeckId: deck.id,
    includeLegendary: true,
  });
  saveAiOpponent(opponent);

  const tournament = createTournament({
    name: `${prefix} Cup`,
    playerDeck: deck,
    totalRounds: 3,
    difficultyCurve: 'normal',
    opponentSource: 'autoGenerated',
    cards,
    aiOpponents: [opponent],
    decks: [deck],
  });
  saveTournament(tournament);

  const game = createNewGameFromDecks(deck, deck, cards);
  saveGame(game, `${prefix} Save`, 'local');

  return backupAllData();
}

describe('dataBackup restore', () => {
  beforeEach(() => {
    createStorageHarness();
  });

  it('restores a valid full backup', () => {
    const backup = seedBackupableData('restore');
    const parsed = parseFullDataBackup(JSON.stringify(backup));

    expect(parsed.preview).toEqual({
      cards: 10,
      decks: 1,
      aiOpponents: 1,
      tournaments: 1,
      saves: 1,
    });

    localStorage.clear();
    restoreFullDataBackup(parsed);

    expect(loadCards()).toHaveLength(10);
    expect(loadDecks()).toHaveLength(1);
    expect(loadAiOpponents()).toHaveLength(1);
    expect(loadTournaments()).toHaveLength(1);
    expect(loadAllSaves()).toHaveLength(1);
  });

  it('rejects an invalid backup before writing anything', () => {
    seedBackupableData('existing');
    const before = readAppStorageSnapshot();

    const invalidBackup = {
      exportVersion: 1,
      exportedAt: new Date().toISOString(),
      type: 'battle-monsters-full-backup',
      storage: {
        [CARDS_KEY]: JSON.stringify({ not: 'an array' }),
      },
    };

    expect(() => parseFullDataBackup(JSON.stringify(invalidBackup))).toThrow(/card array/i);
    expect(readAppStorageSnapshot()).toEqual(before);
  });

  it('prevents partial overwrite when restore fails mid-write', () => {
    const oldBackup = seedBackupableData('old');
    const oldSnapshot = { ...oldBackup.storage };

    localStorage.clear();
    const newBackup = seedBackupableData('new');
    const parsed = parseFullDataBackup(JSON.stringify(newBackup));

    localStorage.clear();
    for (const [storageKey, raw] of Object.entries(oldSnapshot)) {
      localStorage.setItem(storageKey, raw);
    }

    const harness = createStorageHarness();
    for (const [storageKey, raw] of Object.entries(oldSnapshot)) {
      harness.store.set(storageKey, raw);
    }
    harness.failState.key = DECKS_KEY;
    harness.failState.value = parsed.storage[DECKS_KEY] ?? null;

    expect(() => restoreFullDataBackup(parsed)).toThrow(/backup could not be restored|restore failed/i);
    expect(readAppStorageSnapshot()).toEqual(oldSnapshot);
  });

  it('replaces existing data with the restored backup contents', () => {
    seedBackupableData('old');
    const replacementBackup = parseFullDataBackup(JSON.stringify((() => {
      localStorage.clear();
      return seedBackupableData('new');
    })()));

    restoreFullDataBackup(replacementBackup);

    expect(loadCards().every((card) => card.id.startsWith('new-'))).toBe(true);
    expect(loadCards().some((card) => card.id.startsWith('old-'))).toBe(false);
    expect(loadDecks()[0]?.name).toBe('new Deck');
    expect(loadAiOpponents()[0]?.name).toBe('new Coach');
  });
});
