import { COMMON_CREATURE_TYPES, normalizeCreatureTypes, type Card } from '../models/card';
import type { Deck } from '../models/deck';
import { createNewGameFromDecks } from '../engine/rules';
import { isGameState, type GameState } from '../engine/gameState';
import {
  generateAutoDeck,
  type AutoDeckDifficulty,
  type AutoDeckStyle,
} from '../engine/autoDeckBuilder';
import { resolveAiOpponentDeck, type AiOpponent } from './aiOpponentStorage';

const STORAGE_KEY = 'battle-monsters:tournaments';

export type TournamentRoundCount = 3 | 5 | 8;
export type TournamentDifficultyCurve = 'easy' | 'normal' | 'hard' | 'rising';
export type TournamentOpponentSource = 'existingOpponents' | 'autoGenerated';
export type TournamentRoundResult = 'pending' | 'won' | 'lost' | 'draw';
export type TournamentStatus = 'in_progress' | 'won' | 'lost';

export interface TournamentOpponentSnapshot {
  id: string;
  name: string;
  portraitImageUrl?: string;
  difficulty: AutoDeckDifficulty;
  playStyle: AutoDeckStyle;
  preferredCreatureType?: string;
  catchphrase?: string;
  deck: Deck;
}

export interface TournamentRound {
  roundNumber: number;
  opponent: TournamentOpponentSnapshot;
  result: TournamentRoundResult;
}

export interface TournamentProgress {
  id: string;
  name: string;
  playerDeckId: string;
  playerDeck: Deck;
  totalRounds: TournamentRoundCount;
  difficultyCurve: TournamentDifficultyCurve;
  opponentSource: TournamentOpponentSource;
  rounds: TournamentRound[];
  currentRoundIndex: number;
  currentGame: GameState | null;
  status: TournamentStatus;
  startedAt: string;
  updatedAt: string;
}

export interface CreateTournamentOptions {
  name: string;
  playerDeck: Deck;
  totalRounds: TournamentRoundCount;
  difficultyCurve: TournamentDifficultyCurve;
  opponentSource: TournamentOpponentSource;
  cards: Card[];
  aiOpponents: AiOpponent[];
  decks: Deck[];
}

const AUTO_STYLE_SEQUENCE: readonly AutoDeckStyle[] = [
  'balanced',
  'aggressive',
  'defensive',
  'cheap-swarm',
  'big-monsters',
  'random',
];

const NAME_PREFIXES = [
  'Iron',
  'Shadow',
  'Solar',
  'Storm',
  'Frost',
  'Wild',
  'Rune',
  'Blaze',
] as const;

const NAME_SUFFIXES = [
  'Drake',
  'Warden',
  'Fang',
  'Sage',
  'Crusher',
  'Howler',
  'Titan',
  'Scout',
] as const;

function isRoundCount(value: unknown): value is TournamentRoundCount {
  return value === 3 || value === 5 || value === 8;
}

function isDifficultyCurve(value: unknown): value is TournamentDifficultyCurve {
  return value === 'easy' || value === 'normal' || value === 'hard' || value === 'rising';
}

function isOpponentSource(value: unknown): value is TournamentOpponentSource {
  return value === 'existingOpponents' || value === 'autoGenerated';
}

function isRoundResult(value: unknown): value is TournamentRoundResult {
  return value === 'pending' || value === 'won' || value === 'lost' || value === 'draw';
}

function isTournamentStatus(value: unknown): value is TournamentStatus {
  return value === 'in_progress' || value === 'won' || value === 'lost';
}

function isDeckEntry(value: unknown): value is Deck['entries'][number] {
  if (!value || typeof value !== 'object') return false;
  const entry = value as Record<string, unknown>;
  return typeof entry.cardId === 'string' && typeof entry.count === 'number';
}

function isDeck(value: unknown): value is Deck {
  if (!value || typeof value !== 'object') return false;
  const deck = value as Record<string, unknown>;
  return (
    typeof deck.id === 'string' &&
    typeof deck.name === 'string' &&
    Array.isArray(deck.entries) &&
    deck.entries.every(isDeckEntry)
  );
}

function isTournamentOpponentSnapshot(value: unknown): value is TournamentOpponentSnapshot {
  if (!value || typeof value !== 'object') return false;
  const opponent = value as Record<string, unknown>;
  return (
    typeof opponent.id === 'string' &&
    typeof opponent.name === 'string' &&
    (typeof opponent.portraitImageUrl === 'string' ||
      typeof opponent.portraitImageUrl === 'undefined') &&
    (typeof opponent.preferredCreatureType === 'string' ||
      typeof opponent.preferredCreatureType === 'undefined') &&
    (typeof opponent.catchphrase === 'string' || typeof opponent.catchphrase === 'undefined') &&
    (opponent.difficulty === 'easy' ||
      opponent.difficulty === 'normal' ||
      opponent.difficulty === 'hard') &&
    (opponent.playStyle === 'random' ||
      opponent.playStyle === 'balanced' ||
      opponent.playStyle === 'aggressive' ||
      opponent.playStyle === 'defensive' ||
      opponent.playStyle === 'big-monsters' ||
      opponent.playStyle === 'cheap-swarm') &&
    isDeck(opponent.deck)
  );
}

function isTournamentRound(value: unknown): value is TournamentRound {
  if (!value || typeof value !== 'object') return false;
  const round = value as Record<string, unknown>;
  return (
    typeof round.roundNumber === 'number' &&
    isRoundResult(round.result) &&
    isTournamentOpponentSnapshot(round.opponent)
  );
}

function isTournamentProgress(value: unknown): value is TournamentProgress {
  if (!value || typeof value !== 'object') return false;
  const tournament = value as Record<string, unknown>;
  return (
    typeof tournament.id === 'string' &&
    typeof tournament.name === 'string' &&
    typeof tournament.playerDeckId === 'string' &&
    isDeck(tournament.playerDeck) &&
    isRoundCount(tournament.totalRounds) &&
    isDifficultyCurve(tournament.difficultyCurve) &&
    isOpponentSource(tournament.opponentSource) &&
    Array.isArray(tournament.rounds) &&
    tournament.rounds.every(isTournamentRound) &&
    typeof tournament.currentRoundIndex === 'number' &&
    (tournament.currentGame === null || isGameState(tournament.currentGame)) &&
    isTournamentStatus(tournament.status) &&
    typeof tournament.startedAt === 'string' &&
    typeof tournament.updatedAt === 'string'
  );
}

function difficultyRank(difficulty: AutoDeckDifficulty): number {
  if (difficulty === 'easy') return 0;
  if (difficulty === 'normal') return 1;
  return 2;
}

function cloneTournament(tournament: TournamentProgress): TournamentProgress {
  return {
    ...tournament,
    playerDeck: {
      ...tournament.playerDeck,
      entries: tournament.playerDeck.entries.map((entry) => ({ ...entry })),
    },
    rounds: tournament.rounds.map((round) => ({
      ...round,
      opponent: {
        ...round.opponent,
        deck: {
          ...round.opponent.deck,
          entries: round.opponent.deck.entries.map((entry) => ({ ...entry })),
        },
      },
    })),
    currentGame: tournament.currentGame
      ? JSON.parse(JSON.stringify(tournament.currentGame))
      : null,
  };
}

function isFinishedGame(game: GameState | null): game is GameState {
  if (!game) return false;
  return game.winner !== null || (game.players[0].health <= 0 && game.players[1].health <= 0);
}

function normalizeTournament(tournament: TournamentProgress): TournamentProgress {
  return {
    ...tournament,
    name: tournament.name.trim(),
    updatedAt: tournament.updatedAt,
  };
}

function readRaw(): TournamentProgress[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const parsed: unknown = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    return parsed
      .filter(isTournamentProgress)
      .map((tournament) => normalizeTournament(tournament));
  } catch {
    return [];
  }
}

function writeAll(tournaments: TournamentProgress[]): void {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(tournaments));
}

function generateOpponentName(index: number): string {
  const prefix = NAME_PREFIXES[index % NAME_PREFIXES.length];
  const suffix = NAME_SUFFIXES[Math.floor(index / NAME_PREFIXES.length) % NAME_SUFFIXES.length];
  return `${prefix} ${suffix}`;
}

function styleForRound(index: number): AutoDeckStyle {
  return AUTO_STYLE_SEQUENCE[index % AUTO_STYLE_SEQUENCE.length]!;
}

function availableCreatureTypeThemes(cards: Card[]): string[] {
  return COMMON_CREATURE_TYPES.filter((type) =>
    cards.some((card) =>
      normalizeCreatureTypes(card.creatureTypes).some(
        (cardType) => cardType.toLowerCase() === type.toLowerCase(),
      ),
    ),
  );
}

function difficultyForRound(
  curve: TournamentDifficultyCurve,
  index: number,
  totalRounds: TournamentRoundCount,
): AutoDeckDifficulty {
  if (curve === 'easy' || curve === 'normal' || curve === 'hard') {
    return curve;
  }

  const progress = index / (totalRounds - 1);
  if (progress < 0.34) return 'easy';
  if (progress < 0.74) return 'normal';
  return 'hard';
}

function buildAutoGeneratedRounds(
  totalRounds: TournamentRoundCount,
  curve: TournamentDifficultyCurve,
  cards: Card[],
): TournamentRound[] {
  const availableThemes = availableCreatureTypeThemes(cards);
  return Array.from({ length: totalRounds }, (_, index) => {
    const difficulty = difficultyForRound(curve, index, totalRounds);
    const playStyle = styleForRound(index);
    const includeLegendary = difficulty !== 'easy';
    const name = generateOpponentName(index);
    const preferredCreatureType =
      availableThemes.length > 0 ? availableThemes[index % availableThemes.length] : undefined;
    const generatedDeck = generateAutoDeck({
      name: `${name} Deck`,
      difficulty,
      style: playStyle,
      includeLegendary,
      preferredCreatureType,
      cards,
    });

    return {
      roundNumber: index + 1,
      result: 'pending' as const,
      opponent: {
        id: `tournament-auto-${index + 1}`,
        name,
        difficulty,
        playStyle,
        preferredCreatureType,
        deck: {
          id: `tournament-auto-deck-${index + 1}`,
          name: generatedDeck.name,
          entries: generatedDeck.entries,
        },
      },
    };
  });
}

function buildExistingOpponentRounds(
  totalRounds: TournamentRoundCount,
  curve: TournamentDifficultyCurve,
  aiOpponents: AiOpponent[],
  decks: Deck[],
  cards: Card[],
): TournamentRound[] {
  if (aiOpponents.length < totalRounds) {
    throw new Error(`Need at least ${totalRounds} AI opponents to build this tournament.`);
  }

  const sorted = [...aiOpponents].sort((a, b) => {
    const aRank = difficultyRank(a.difficulty);
    const bRank = difficultyRank(b.difficulty);

    if (curve === 'easy' || curve === 'rising') {
      return aRank - bRank || a.name.localeCompare(b.name);
    }
    if (curve === 'hard') {
      return bRank - aRank || a.name.localeCompare(b.name);
    }

    const aDistance = Math.abs(aRank - 1);
    const bDistance = Math.abs(bRank - 1);
    return aDistance - bDistance || aRank - bRank || a.name.localeCompare(b.name);
  });

  return sorted.slice(0, totalRounds).map((opponent, index) => ({
    roundNumber: index + 1,
    result: 'pending',
    opponent: {
      id: opponent.id,
      name: opponent.name,
      portraitImageUrl: opponent.portraitImageUrl,
      difficulty: opponent.difficulty,
      playStyle: opponent.playStyle,
      preferredCreatureType: opponent.preferredCreatureType,
      catchphrase: opponent.catchphrase,
      deck: resolveAiOpponentDeck(opponent, decks, cards),
    },
  }));
}

export function loadTournaments(): TournamentProgress[] {
  return readRaw().sort(
    (a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime(),
  );
}

export function getTournamentById(id: string): TournamentProgress | undefined {
  return readRaw().find((tournament) => tournament.id === id);
}

export function saveTournament(tournament: TournamentProgress): void {
  const normalized = normalizeTournament({
    ...tournament,
    updatedAt: new Date().toISOString(),
  });
  const tournaments = readRaw();
  const index = tournaments.findIndex((existing) => existing.id === normalized.id);
  if (index >= 0) {
    tournaments[index] = normalized;
  } else {
    tournaments.push(normalized);
  }
  writeAll(tournaments);
}

export function deleteTournament(id: string): void {
  const tournaments = readRaw();
  const next = tournaments.filter((tournament) => tournament.id !== id);
  if (next.length === tournaments.length) {
    throw new Error(`Tournament with id "${id}" not found.`);
  }
  writeAll(next);
}

export function createTournament(options: CreateTournamentOptions): TournamentProgress {
  const name = options.name.trim();
  if (!name) {
    throw new Error('Tournament name is required.');
  }

  const rounds =
    options.opponentSource === 'autoGenerated'
      ? buildAutoGeneratedRounds(options.totalRounds, options.difficultyCurve, options.cards)
      : buildExistingOpponentRounds(
          options.totalRounds,
          options.difficultyCurve,
          options.aiOpponents,
          options.decks,
          options.cards,
        );

  const startedAt = new Date().toISOString();

  return {
    id: crypto.randomUUID(),
    name,
    playerDeckId: options.playerDeck.id,
    playerDeck: {
      ...options.playerDeck,
      entries: options.playerDeck.entries.map((entry) => ({ ...entry })),
    },
    totalRounds: options.totalRounds,
    difficultyCurve: options.difficultyCurve,
    opponentSource: options.opponentSource,
    rounds,
    currentRoundIndex: 0,
    currentGame: createNewGameFromDecks(options.playerDeck, rounds[0]!.opponent.deck, options.cards),
    status: 'in_progress',
    startedAt,
    updatedAt: startedAt,
  };
}

export function updateTournamentGame(
  tournament: TournamentProgress,
  game: GameState,
): TournamentProgress {
  return {
    ...cloneTournament(tournament),
    currentGame: game,
    updatedAt: new Date().toISOString(),
  };
}

export function restartCurrentRound(
  tournament: TournamentProgress,
  cards: Card[],
): TournamentProgress {
  const round = tournament.rounds[tournament.currentRoundIndex];
  if (!round) {
    throw new Error('Current tournament round was not found.');
  }

  const next = cloneTournament(tournament);
  next.rounds[next.currentRoundIndex] = {
    ...round,
    result: 'pending',
  };
  next.currentGame = createNewGameFromDecks(next.playerDeck, round.opponent.deck, cards);
  next.updatedAt = new Date().toISOString();
  return next;
}

export function advanceTournament(
  tournament: TournamentProgress,
  cards: Card[],
): TournamentProgress {
  if (!isFinishedGame(tournament.currentGame)) {
    throw new Error('Current tournament game is not finished yet.');
  }

  if (tournament.currentGame.winner === null) {
    throw new Error('Drawn rounds must be replayed before advancing.');
  }

  const next = cloneTournament(tournament);
  const round = next.rounds[next.currentRoundIndex];
  if (!round) {
    throw new Error('Current tournament round was not found.');
  }

  if (tournament.currentGame.winner === 0) {
    round.result = 'won';
    if (next.currentRoundIndex === next.rounds.length - 1) {
      next.status = 'won';
    } else {
      next.currentRoundIndex += 1;
      const upcoming = next.rounds[next.currentRoundIndex]!;
      next.currentGame = createNewGameFromDecks(next.playerDeck, upcoming.opponent.deck, cards);
    }
  } else {
    round.result = 'lost';
    next.status = 'lost';
  }

  next.updatedAt = new Date().toISOString();
  return next;
}
