import { beforeEach, describe, expect, it, vi } from 'vitest';
import { cardWithId } from '../models/card';
import type { Card } from '../models/card';
import type { Deck } from '../models/deck';
import type { GameState } from '../engine/gameState';
import { createAiOpponent } from './aiOpponentStorage';
import {
  advanceTournament,
  createTournament,
  deleteTournament,
  loadTournaments,
  restartCurrentRound,
  saveTournament,
  updateTournamentGame,
} from './tournamentStorage';

function stubStorage() {
  const store = new Map<string, string>();
  vi.stubGlobal('localStorage', {
    getItem: (key: string) => store.get(key) ?? null,
    setItem: (key: string, value: string) => {
      store.set(key, value);
    },
    removeItem: (key: string) => {
      store.delete(key);
    },
    clear: () => store.clear(),
  });
}

function gameWithWinner(
  game: GameState,
  winner: 0 | 1 | null,
  player1Health: number,
  player2Health: number,
): GameState {
  return {
    ...game,
    winner,
    players: [
      { ...game.players[0], health: player1Health },
      { ...game.players[1], health: player2Health },
    ],
  };
}

function makeCard(id: string, cost: number, attack: number, health: number, rarity: Card['rarity'] = 'common'): Card {
  return cardWithId(id, {
    name: id,
    imageUrl: `data:image/webp;base64,${id}`,
    cost,
    attack,
    health,
    flavorText: `${id} flavor`,
    rarity,
  });
}

const cards: Card[] = [
  makeCard('m1', 1, 1, 2),
  makeCard('m2', 1, 2, 1),
  makeCard('m3', 2, 2, 3),
  makeCard('m4', 2, 3, 2),
  makeCard('m5', 3, 3, 4),
  makeCard('m6', 3, 4, 3, 'rare'),
  makeCard('m7', 4, 4, 4),
  makeCard('m8', 4, 2, 6, 'rare'),
  makeCard('m9', 5, 6, 5),
  makeCard('m10', 6, 7, 7, 'rare'),
  makeCard('m11', 7, 8, 8, 'legendary'),
];

const playerDeck: Deck = {
  id: 'player-deck',
  name: 'Hero Deck',
  entries: cards.slice(0, 10).map((card) => ({ cardId: card.id, count: 3 })),
};

const savedAiDeck: Deck = {
  id: 'ai-deck',
  name: 'Boss Deck',
  entries: cards.slice(0, 10).map((card) => ({
    cardId: card.id,
    count: 3,
  })),
};

const existingOpponents = [
  createAiOpponent({
    name: 'Coach Bot',
    difficulty: 'easy',
    playStyle: 'balanced',
    deckSource: 'savedDeck',
    savedDeckId: savedAiDeck.id,
    includeLegendary: true,
  }),
  createAiOpponent({
    name: 'Claw Bot',
    difficulty: 'normal',
    playStyle: 'aggressive',
    deckSource: 'autoGenerated',
    includeLegendary: false,
  }),
  createAiOpponent({
    name: 'Wall Bot',
    difficulty: 'hard',
    playStyle: 'defensive',
    deckSource: 'autoGenerated',
    includeLegendary: true,
  }),
];

describe('tournamentStorage', () => {
  beforeEach(() => {
    stubStorage();
  });

  it('creates and saves an auto-generated tournament', () => {
    const tournament = createTournament({
      name: '  Forest Cup  ',
      playerDeck,
      totalRounds: 3,
      difficultyCurve: 'rising',
      opponentSource: 'autoGenerated',
      cards,
      aiOpponents: [],
      decks: [playerDeck, savedAiDeck],
    });

    expect(tournament.name).toBe('Forest Cup');
    expect(tournament.rounds).toHaveLength(3);
    expect(tournament.rounds.map((round) => round.opponent.difficulty)).toEqual([
      'easy',
      'normal',
      'hard',
    ]);
    expect(tournament.currentGame).toBeTruthy();

    saveTournament(tournament);
    expect(loadTournaments()).toHaveLength(1);
  });

  it('requires enough existing AI opponents for existing-opponent tournaments', () => {
    expect(() =>
      createTournament({
        name: 'League',
        playerDeck,
        totalRounds: 5,
        difficultyCurve: 'normal',
        opponentSource: 'existingOpponents',
        cards,
        aiOpponents: existingOpponents,
        decks: [playerDeck, savedAiDeck],
      }),
    ).toThrow(/Need at least 5 AI opponents/i);
  });

  it('advances to the next round after a player win', () => {
    const tournament = createTournament({
      name: 'League',
      playerDeck,
      totalRounds: 3,
      difficultyCurve: 'easy',
      opponentSource: 'autoGenerated',
      cards,
      aiOpponents: [],
      decks: [playerDeck, savedAiDeck],
    });

    const wonGame = gameWithWinner(tournament.currentGame!, 0, 10, 0);

    const updated = updateTournamentGame(tournament, wonGame);
    const advanced = advanceTournament(updated, cards);

    expect(advanced.rounds[0]?.result).toBe('won');
    expect(advanced.currentRoundIndex).toBe(1);
    expect(advanced.status).toBe('in_progress');
    expect(advanced.currentGame?.turnNumber).toBe(1);
  });

  it('ends the tournament after a player loss', () => {
    const tournament = createTournament({
      name: 'League',
      playerDeck,
      totalRounds: 3,
      difficultyCurve: 'hard',
      opponentSource: 'autoGenerated',
      cards,
      aiOpponents: [],
      decks: [playerDeck, savedAiDeck],
    });

    const lostGame = gameWithWinner(tournament.currentGame!, 1, 0, 7);

    const updated = updateTournamentGame(tournament, lostGame);
    const finished = advanceTournament(updated, cards);

    expect(finished.rounds[0]?.result).toBe('lost');
    expect(finished.status).toBe('lost');
  });

  it('restarts the current round after a draw', () => {
    const tournament = createTournament({
      name: 'League',
      playerDeck,
      totalRounds: 3,
      difficultyCurve: 'normal',
      opponentSource: 'autoGenerated',
      cards,
      aiOpponents: [],
      decks: [playerDeck, savedAiDeck],
    });

    const drawGame = gameWithWinner(tournament.currentGame!, null, 0, 0);

    const updated = updateTournamentGame(tournament, drawGame);
    const restarted = restartCurrentRound(updated, cards);

    expect(restarted.currentRoundIndex).toBe(0);
    expect(restarted.rounds[0]?.result).toBe('pending');
    expect(restarted.currentGame?.winner).toBeNull();
    expect(restarted.currentGame?.turnNumber).toBe(1);
  });

  it('deletes saved tournaments', () => {
    const tournament = createTournament({
      name: 'League',
      playerDeck,
      totalRounds: 3,
      difficultyCurve: 'normal',
      opponentSource: 'existingOpponents',
      cards,
      aiOpponents: existingOpponents,
      decks: [playerDeck, savedAiDeck],
    });

    saveTournament(tournament);
    deleteTournament(tournament.id);

    expect(loadTournaments()).toEqual([]);
  });
});
